name: Tests

on: [push, pull_request]

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: ${{ runner.os }}-venv-${{ hashFiles('poetry.lock') }}

      - name: Setup poetry
        run: |
          pip install poetry
          poetry install -n --no-root
          poetry shell

      - name: Check code formatting with black
        run: poe black --diff --check